# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246b898ea2293f7558bfa9bece28ff0b00c0d528b0ad64676094e6e1a504a8db0e03891ca5a0227c6c2a08444495b35e476bd39229588c816a9653aaf2ff8bc8

test:
  secret_key_base: ebe29be77532d17f6cc6f16417e9b45228a83f55cee3b5f7ada34268d127e504585b77998a17a459f6870a4ec657a4437b1ac621170c4be5c40e24377a3e36a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
